Repository Shastra-OS/site, pull requests merged in 2022-10, with the labels that each got.

#52 docs
  pages/Footer.js
  public/workbox-946f13af.js
  public/workbox-eac1af49.js
  public/workbox-eac1af49.js.map
Labels: invalid

#53 Updating the readme file
  README.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, Priority #3

#66 mockup
  components/mockups/SurfaceStudio.js
  pages/index.js
Labels: enhancement, invalid

#70 Added screenshots in Homepage
  components/mockups/window3.js
  pages/index.js
  public/screenshots/cinnamon.webp
  public/screenshots/cinnamonrep.png
  public/screenshots/screenshot3.png
  public/screenshots/screnshot2.png
Labels: bug, hacktoberfest, hacktoberfest-accepted

#73 Fixed Overflowing pfps
  styles/Home.module.css
Labels: hacktoberfest, hacktoberfest-accepted, minor

#77 Fixed spacing problems and some typos
  pages/about.js
  pages/install.js
Labels: documentation, hacktoberfest, hacktoberfest-accepted, minor

#78 Light Dark Theme #57
  components/Header.js
  styles/Home.module.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, Priority #2

#79 minor tweaks
  .gitpod.yml
  next.config.js
  pages/devs.js
  pages/install.js
  public/workbox-327c579b.js
  public/workbox-327c579b.js.map
  public/workbox-588899ac.js
  yarn.lock
Labels: minor

#81 Key issue on team page - fix
  pages/devs.js
Labels: help wanted, hacktoberfest, hacktoberfest-accepted, Priority #2

#84 docs(index.js): minor grammatical improvement to Shastra OS homepage
  pages/index.js
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted, Priority #2

#88 Changed colour palette
  pages/index.js
  styles/Home.module.css
  styles/globals.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, Priority #3, minor

#91 Fix Macbook image on homepage (close #90)
  components/mockups/Macbook1.js
Labels: bug, hacktoberfest, hacktoberfest-accepted, Priority #2

#93 Fix header buttons consistency (close 92)
  styles/Home.module.css
Labels: hacktoberfest, hacktoberfest-accepted, Priority #2

#101 [Enhancement] Matched dark mode header and footer
  styles/Home.module.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, Priority #3

#102 resources.md
  RESOURCES.md
  yarn.lock
Labels: minor

#103 add <br> for medium screens where buttons are not visible and edit cs…
  pages/opensource.js
  styles/Home.module.css
  styles/globals.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
